platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def working_pods
  
  # Rx
  pod 'RxCocoa', '~> 6.5.0'
  pod 'Moya/RxSwift', '~> 15.0.0'
  
  # Development
  pod 'SwiftLint', '~> 0.46.5'
  pod 'Wormholy', '~> 1.6.5', :configurations => ['Debug']
end

def testing_pods
  
end

target 'TodoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for TodoApp
  working_pods

  target 'TodoAppTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'TodoAppUITests' do
    # Pods for testing
    testing_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
